# Generated by Django 5.1.1 on 2024-10-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0002_category_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
