# Generated by Django 5.1.1 on 2024-10-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0004_category_created_at_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
