# Generated by Django 4.2.16 on 2024-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0006_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(null=True, upload_to='media/upload'),
        ),
    ]
